#!/bin/bash

# compair local spider output to EasyConfig. Do we have local modules
# that are not part of EB?

# Create a list of all EasyConfigs
ec=/app/software/EasyBuild/4.5.2/easybuild/easyconfigs
[[ -f ecList.txt ]] && rm ecList.txt
for p in {a..z}; do
    ls -C1 $ec/$p >>ecList.txt
done

# The Hutch has modules that will never make it upstream to EasyBuild
source exclude.sh
echo Exclude List: $exclude

# list of installed modules generated by 
# spider=/app/lmod/lmod/libexec/spider
# module_dir=/app/modules
# $spider -o spider-json ${module_dir}/bio:${module_dir}/math:${module_dir}/chem | \
# python3 -mjson.tool >${docs_dir}/modules-${os_ver}.json | \
# listModules.py > list.txt
installed=list.txt

for m in `cat $installed`; do
    f=${m:0:1}  # first character of module
    first=${f,,}  # lower case
    first=`echo $first | xargs`
    found=`grep $m ecList.txt`
    case=`grep -i $m ecList.txt`
    if grep -q $m <<< "$exclude"; then
       continue
    fi
    if grep -q $m <<< "$found" ; then
        : echo Found: $m
    elif [[ $m == $case ]]; then
        echo $m Mismatch
    else
        echo Not found: $m \<$found\>
    fi
done
