#!/usr/bin/env python3

"""
Compare two LMOD JSON spider output files.

Goal: for supporting multible architectures, ensure that Module lists match between
      clusters

    input for this script is generated by `create_modules_list.sh`

    The JSON spider output is relative to /scripts

"""

from pprint import pprint
import json
import sys
import os
import re
import distro
from packaging import version
from toolchain import Toolchain as TC

__author__ = "John Dey"
__date__ = "Jan 2026"
__version__ = "1.0.0"

def create_json_path(arch, catalog):
    """ create path to LMOD JSON spider files
    path asumes you are working in an EB repo
    """
    distro_version = distro.version()
    path = f"../docs/sw_inventory/{arch}-{catalog}-modules-{distro_version}.json"
    if os.path.isfile(path):
        return path
    else:
        print(f"could not find file: {path}", file=sys.stderr)
        sys.exit(1)


def read_spider_json(path, mod_list):
    with open(path, 'r') as file:
        json_data = file.read()
        data = json.loads(json_data)

    packages = data.keys()
    slist = sorted(packages)

    for mod_name in slist:
       versions = data[mod_name]
       for lua in versions:
           mod_list.append(f"{mod_name} {versions[lua]['Version']}.eb")


def diff_module_lists(mod_lista, mod_listb):
    """ Diff two lists. Don't do a full compare between lists, but
    only show itmes that are missing from list-b.

    input are lists, the elements of lists is text.
    output items from lista that are not in listb
    """
    set_b = set(mod_listb)
    return [item for item in mod_lista if item not in set_b]

def find_ec(mod_list):
    """
    locate the source for EasyConfigs. EasyBuild must be loaded to access $EBEASYBUILDROOT
    """
    global eb_path, repo_path

    not_found = []
    for eb in mod_list:
        first = eb[0].lower()
        (mod_name, version) = eb.split()
        full_eb_path= os.path.join(eb_path, first, mod_name, f"{mod_name}-{version}")
        full_repo_path= os.path.join(repo_path, first, mod_name, f"{mod_name}-{version}")
        if not os.path.exists(full_eb_path):
            if not os.path.exists(full_repo_path):
                not_found.append(f"{mod_name}-{version}")
    return not_found


def usage():
    print("Three arguments needed, inventory type 'bio' or 'all' and two architecures to compare")
    print("spiderDiff [bio|all] arch1 arch2")

if __name__ == '__main__':
    global eb_path, repo_path
    debug = False

    if len(sys.argv) != 4:
       usage()
       sys.exit(1)
    eb_root = os.environ.get('EBROOTEASYBUILD')
    if not eb_root:
        print("EasyBuild module must be loaded. ml EasyBuild")
        sys.exit(1)
    eb_path = f"{eb_root}/easybuild/easyconfigs/"
    dirname = os.path.dirname(__file__)
    repo_path = os.path.join(dirname, "../easyconfigs")
    arch1_json = create_json_path(sys.argv[2], sys.argv[1])
    arch2_json = create_json_path(sys.argv[3], sys.argv[1])
    if debug:
        print(f"compare: {arch1_json} {arch2_json}", file=sys.stderr)
    arch1_modules = []
    arch2_modules = []
    read_spider_json(arch1_json, arch1_modules)
    read_spider_json(arch2_json, arch2_modules)
    missing = diff_module_lists(arch1_modules, arch2_modules)
    not_found = find_ec(missing)
    print("#!/bin/bash\n\n")
    for x in missing:
        if x not in not_found:
            print(f"eb {x.replace(' ', '-')} --robot >/dev/null 2>&1")
            print(f"if [[ $? == 0 ]]; then echo Good: '{x}'; else echo 'Failed: {x}'; fi")
        else:
            pass
