
title: Slate theme
description: Slate is a theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-slate

collections:
  Python:
    output: true
    permalink: /:collection/:path/
    layout: page
  R:
    output: true
    permalink: /:collection/:path/
    layout: page
  Dot:
    output: true
    permalink: /:collection/:path/
    layout: page

# Reading Files
include:
  - _layouts
  - assets
  - _pages

theme: jekyll-theme-slate
