
title: Fred Hutch Scientific Software
description: Easybuild Easyconfigs for Scientific Software
show_downloads: true
logo: 
google_analytics:
theme: jekyll-theme-minimal

collections:
  Python:
    output: true
    permalink: /:collection/:path/
    layout: post
  R:
    output: true
    permalink: /:collection/:path/
    layout: post
  Dot:
    output: true
    permalink: /:collection/:path/
    layout: post

# Reading Files
include:
  - _layouts
  - assets
  - _pages
