title: Fred Hutch Scientific Software
logo: /assets/img/logo.png
description: Fred Hutch Easybuild Easyconfigs for Scientific Software. 
show_downloads: false
google_analytics:
theme: jekyll-theme-slate

collections:
  R:
    output: true
    permalink: /:collection/:path/
    layout: default 
  Python:
    output: true
    permalink: /:collection/:path/
    layout: default 
  Dot:
    output: true
    permalink: /:collection/:path/
    layout: default 
