title: Fred Hutch Scientific Software
logo: /assets/img/logo.png
description: Fred Hutch Easybuild Easyconfigs for Scientific Software. 
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal

baseurl: "/easybuild-life-sciences"

collections:
  R:
    output: true
    layout: post
    permalink: /:collection/:path
  Python:
    output: true
    layout: post 
    permalink: /:collection/:path
  Dot:
    output: true
    layout: post 
    permalink: /:collection/:path/
